// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"Go-000/Week04/configs"
	"Go-000/Week04/internal/dao"
	"Go-000/Week04/internal/db/mysql"
)

// Injectors from wire.go:

func InitUserSrv() *UserSrv {
	viper := configs.NewConfig()
	userDB := mysql.NewUserDB(viper)
	userDao := dao.NewUserDao(userDB)
	userSrv := NewUserSrv(userDao)
	return userSrv
}
